### ISSUE TITLE
cobalts.net/About/NinjaWolf064 returns 404 error

### ISSUE THREAD

**Issue by NinjaWolf064** [CobaltsDev/CobaltsDev.github.io#4]
Whenever I try to access /About/NinjaWolf064 the server returns a 404 error. May by it's because it uses PHP instead of HTML?

**Comment by NinjaWolf064** [comment]
Also, when I try to access index.php, Google Chrome tries to download it.

**Comment by a-Sharp-a** [comment]
Yes

**Comment by a-Sharp-a** [comment]
It is because it is php. Github Pages only supports static webpages
