### ISSUE TITLE
todo.md is unclear

### ISSUE THREAD

**Issue by NinjaWolf064** [CobaltsDev/CobaltsDev.github.io#7]
Item 5 on todo.md is unclear. Could whoever wrote this please clarify? For reference, the text is (This is mainly for Jacob and Josh) Make a syle for a contact information table.

**Comment by a-Sharp-a** [comment]
I said make a style for a contacts sheet, but that was when we all had different emails for ourselves

**Comment by NinjaWolf064** [comment]
So do we cross that out?
